name: CookieMonster
main: com.pi.coelho.CookieMonster.CookieMonster
version: 1.5.0.1
authors: [jascotty2, Coelho]
commands:
  cookiemonster:
    description: Admin Commands
    usage: /<command> [reload|region define/list/remove]
    aliases: [cm]